# Generated by Django 5.1.1 on 2024-09-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0002_detectionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionrecord',
            name='camera',
        ),
        migrations.DeleteModel(
            name='CameraLocation',
        ),
        migrations.DeleteModel(
            name='DetectionRecord',
        ),
    ]
