# Generated by Django 5.1.1 on 2024-09-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handling_model', '0003_remove_detectionrecord_camera_delete_cameralocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=1000)),
                ('longitude', models.FloatField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detected_date', models.DateTimeField(auto_created=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling_model.cameralocation')),
            ],
        ),
    ]
