# Generated by Django 5.1.1 on 2024-09-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetectionRecord',
            new_name='detected_database',
        ),
    ]
