# Generated by Django 5.1.1 on 2024-09-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0005_rename_detectionrecord_detected_database'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detected_database',
        ),
    ]
