# Generated by Django 5.1.1 on 2024-09-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0006_delete_detected_database'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraLocation',
            new_name='Located_of_camera',
        ),
    ]
