# Generated by Django 5.1.1 on 2024-09-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0007_rename_cameralocation_located_of_camera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Located_of_camera',
        ),
    ]
