# Generated by Django 5.1.1 on 2024-09-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handling_model', '0008_delete_located_of_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Located_of_camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=1000)),
                ('longitude', models.FloatField(max_length=1000)),
            ],
        ),
    ]
