# Generated by Django 5.1.1 on 2024-09-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0009_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Located_of_camera',
            new_name='Location_of_camera',
        ),
    ]
