# Generated by Django 5.1.1 on 2024-09-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0010_rename_located_of_camera_location_of_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='detected_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detected_date', models.DateTimeField(auto_created=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling_model.location_of_camera')),
            ],
        ),
    ]
