# Generated by Django 5.1.1 on 2024-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling_model', '0011_detected_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected_database',
            name='Detected_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
