# Generated by Django 5.1.1 on 2024-09-27 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Reason_for_membership',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity',
            field=models.ImageField(default='images/profile.jpg', upload_to='identity_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='Not required', max_length=100),
        ),
    ]
